# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  run-tests:

    name: Build and test
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./test_app

    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s
          --health-retries 5 
    steps:
    - uses: actions/checkout@v4
    - name: list files 
      run: pwd && ls -la 
    - name: Set up Phoenix
      uses: erlef/setup-beam@v1 
      with:
        elixir-version: '1.19.3' # [Required] Define the Elixir version
        otp-version: '28'      # [Required] Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: test_app/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix- 
    - name: list fils 
      run: pwd && ls -la 
    - name: Install dependencies
      run: mix deps.get
    - name: setup assets
      run: mix assets.setup
    - name: compile depenndencies
      run: mix deps.compile
    - name: Run tests
      run: mix test
      env:
        DB_PASSWORD: postgres
        DB_HOST: postgres



